### PR TITLE
UI Profile

### PR DESCRIPTION
**Pull request by LazzyGeek**

### CODE REVIEW

**Comment by LazzyGeek** [comment]
Hi Vaibhav, 
Please see if you would be able to merge it to development .
Thank you

**Review by Va1bhav07 — DISMISSED** [review]

**Review by Va1bhav07 — CHANGES_REQUESTED** [review]
Your PR can not be merged it has conflicts with development branch and since the PR is raised from forked repo I cannt do the changes as i dont have access to your repo

**Comment by LazzyGeek** [comment]
.

**Comment by LazzyGeek** [comment]
Requested changes has been made, please review

**Pull request closed without merging**
